// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using UstSoft.EnglishTraining.UnitOfWork;

namespace UstSoft.EnglishTraining.UnitOfWork.Migrations
{
    [DbContext(typeof(EnglishTrainingDbContext))]
    [Migration("20171127173531_create_verbs")]
    partial class create_verbs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UstSoft.EnglishTraining.UnitOfWork.Entities.Verb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Infinitive")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("IsIrregular");

                    b.Property<string>("PastIndefinite")
                        .HasMaxLength(100);

                    b.Property<string>("PastParticiple")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Verbs");
                });
#pragma warning restore 612, 618
        }
    }
}
